//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Competidor
{
	id: number;
	codigo: string;
	nombre: string;
	calle: string;
	latitud: number;
	longitud: number;
	marcador: boolean;
	observar: boolean;
	marcaId: number;
	zonaDePrecioId: number;
	marca: Marca;
	zonaDePrecio: ZonaDePrecio;
}
export interface Marca
{
	id: number;
	codigo: string;
	nombre: string;
}
export interface ZonaDePrecio
{
	id: number;
	codigo: string;
	nombre: string;
}
